# Smart Sales Prediction System
## Data Analysis Module

This notebook loads `Advertising.csv`, cleans the dataset, checks data quality, saves the cleaned output, and generates all requested exploratory charts.

In [1]:
from pathlib import Path
import sys
import pandas as pd
from IPython.display import display

project_root = Path.cwd()
if not (project_root / 'Advertising.csv').exists():
    project_root = project_root.parent

sys.path.insert(0, str(project_root / 'src'))

from data_loader import load_dataset, dataset_overview
from preprocessing import clean_dataset, dataset_quality_report, save_cleaned_dataset
from eda import create_eda_plots, generate_insights_markdown

## 1. Load Dataset

In [2]:
raw_data = load_dataset(project_root / 'Advertising.csv')
overview = dataset_overview(raw_data)

print('Shape:', overview['shape'])
display(overview['head'])
print(overview['info'])
display(overview['describe'])

Shape: (500, 6)

  Campaign_ID  TV_Ad_Budget  Radio_Ad_Budget Newspaper_Ad_Budget  Sales Region
0    CMP-0250          55.4             31.0                57.0   10.1   West
1    CMP-0433         171.3             49.4            16.3 USD   22.7  East
2    CMP-0262          80.9             31.9               112.5   12.9   WEST
3    CMP-0108          90.4              0.3            23.2 USD    8.7   West
4    CMP-0184         287.6             43.0               $71.8   26.2  North

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Campaign_ID          500 non-null    str
 1   TV_Ad_Budget         476 non-null    float64
 2   Radio_Ad_Budget      476 non-null    float64
 3   Newspaper_Ad_Budget  500 non-null    str
 4   Sales                474 non-null    float64
 5   Region               500 non-null    str
dtypes: float64(3), str(3)
memory usage: 23.6 KB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Campaign_ID,500,485,CMP-0250,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TV_Ad_Budget,476.0,NaN,NaN,NaN,151.943194,99.442739,0.7,74.625,152.45,220.825,800.324532
Radio_Ad_Budget,476.0,NaN,NaN,NaN,24.109874,15.550593,-40.3,10.75,24.55,37.225,49.6
Newspaper_Ad_Budget,500,416,57.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sales,474.0,NaN,NaN,NaN,14.816783,8.446226,1.6,10.8,14.15,17.875,102.615841
Region,500,17,East,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2. Clean Dataset

The cleaning step removes `Campaign_ID`, strips currency markers, removes extra spaces, standardizes `Region`, converts budgets and sales to floats, and drops duplicate rows.

In [3]:
cleaned_data = clean_dataset(raw_data)
quality_report = dataset_quality_report(cleaned_data)
cleaned_path = save_cleaned_dataset(cleaned_data, project_root / 'data' / 'cleaned_advertising.csv')

display(cleaned_data.head())
display(quality_report['missing_values'])
print('Duplicate rows:', quality_report['duplicate_rows'])
print('Incorrect dtypes:', quality_report['incorrect_dtypes'])
print('Saved cleaned dataset to:', cleaned_path)

   TV_Ad_Budget  Radio_Ad_Budget  Newspaper_Ad_Budget  Sales Region
0          55.4             31.0                 57.0   10.1   West
1         171.3             49.4                 16.3   22.7   East
2          80.9             31.9                112.5   12.9   West
3          90.4              0.3                 23.2    8.7   West
4         287.6             43.0                 71.8   26.2  North

TV_Ad_Budget           24
Radio_Ad_Budget        24
Newspaper_Ad_Budget     0
Sales                   0
Region                  0
dtype: int64

Duplicate rows: 0
Incorrect dtypes: {}
Saved cleaned dataset to: c:\Users\DC\Desktop\Smart-Sales-Prediction-System\data\cleaned_advertising.csv

## 3. Exploratory Data Analysis

The following charts are saved to `outputs/graphs/`.

In [4]:
graphs_dir = project_root / 'outputs' / 'graphs'
generated_graphs = create_eda_plots(cleaned_data, graphs_dir)
display(pd.DataFrame({'plot': list(generated_graphs.keys()), 'file': [str(path) for path in generated_graphs.values()]}))

                  plot                                               file
0            histogram  c:\Users\DC\Desktop\Smart-Sales-Prediction-Sys...
1              boxplot  c:\Users\DC\Desktop\Smart-Sales-Prediction-Sys...
2  correlation_heatmap  c:\Users\DC\Desktop\Smart-Sales-Prediction-Sys...
3             pairplot  c:\Users\DC\Desktop\Smart-Sales-Prediction-Sys...
4   sales_distribution  c:\Users\DC\Desktop\Smart-Sales-Prediction-Sys...
5         tv_ad_budget  c:\Users\DC\Desktop\Smart-Sales-Prediction-Sys...
6      radio_ad_budget  c:\Users\DC\Desktop\Smart-Sales-Prediction-Sys...
7  newspaper_ad_budget  c:\Users\DC\Desktop\Smart-Sales-Prediction-Sys...
8      region_vs_sales  c:\Users\DC\Desktop\Smart-Sales-Prediction-Sys...

## 4. Insights

The markdown below summarizes the main relationships observed in the data.

In [5]:
generate_insights_markdown(cleaned_data)

## Key Insights

- **TV_Ad_Budget** has the strongest relationship with sales at **0.36**.
- **East** has the highest average sales at **15.70**.
- The sales distribution should be checked for skewness and outliers because advertising response is rarely perfectly symmetric.
- Compare the scatterplots to see whether budget increases appear to produce diminishing returns.